version: '3.9'

services:
  alpine-docker:
    image: yobasystems/alpine-docker:dind
    container_name: alpine-docker
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
