version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /volume1/docker/config/gluetun:/config
      - /volume1/docker/universalmedia:/data
    environment:

      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=NORDVPN
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER= #enter vpn email here
      - OPENVPN_PASSWORD= #enter VPN password here
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=America/New_York
    network_mode: SynologyDockerNetwork
